apiVersion: v1
kind: Service
metadata:
  name: mysql-v1
  namespace: demo-app
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    version: v1
  type: ClusterIP
