apiVersion: v1
kind: Service
metadata:
  name: backend-v1
  namespace: demo-app
  labels:
    app: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
    version: v1
  type: ClusterIP
