apiVersion: v1
kind: Service
metadata:
  name: frontend-v1
  namespace: demo-app
  labels:
    app: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
    version: v1
  type: NodePort
