apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  namespace: demo-app
  labels:
    app: frontend
    version: v1
    env: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
        env: poc
    spec:
      containers:
      - name: frontend
        image: motarski/fake-service:v0.26.2
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
        readinessProbe:
          tcpSocket:
            port: http
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "frontend-v1"
        - name: "MESSAGE"
          value: "Hello From frontend (v1)!"
        - name: "UPSTREAM_URIS"
          value: "backend-v1:8080,http://backend-v2:8080,http://backend-v3:8080"
