apiVersion: v1
kind: Service
metadata:
  name: backend-v1
  labels:
    app: backend-v1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend-v1